"""
Django settings for starnavi_demo project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "zpfol173(u=17&@1y@=4v_$$oy(wvey&oo!ef0zt&i1)*(9pku"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Test mode hack - https://stackoverflow.com/a/11366998
UNIT_TESTING = sys.argv[1:2] == ["test"]

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    # 'django.contrib.sessions',
    # Messages app not needed for REST API projects
    # 'django.contrib.messages',
    "django.contrib.staticfiles",
    "rest_framework",
    "djoser",
    "dry_rest_permissions",
    "medium",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "starnavi_demo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "starnavi_demo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"

# Specifying custom user model is recommended when starting a new project - saves migration headaches later

AUTH_USER_MODEL = "medium.User"

# DRF

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

# Custom configuration

if not UNIT_TESTING:
    MEDIUM_CLEARBIT_API_KEY = os.environ.get("CLEARBIT_API_KEY")
    MEDIUM_CLEARBIT_ENRICHMENT = os.environ.get("CLEARBIT_ENRICHMENT") == "1"
    MEDIUM_EMAILHUNTER_API_KEY = os.environ.get("EMAILHUNTER_API_KEY")
    MEDIUM_EMAILHUNTER_VALIDATION = os.environ.get("EMAILHUNTER_VALIDATION")
else:
    # Clearbit and emailhunter clients should be mocked
    MEDIUM_CLEARBIT_API_KEY = "fake key"
    MEDIUM_CLEARBIT_ENRICHMENT = False
    MEDIUM_EMAILHUNTER_API_KEY = "fake key"
    MEDIUM_EMAILHUNTER_VALIDATION = False
